# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
tues = Post.create title: "Tuesdays are awesome", body: "But I'm the oldest. The matriarch if you will. Sorry, some of my students are arguing the significance of the shankbone on the seder plate. But we do not - NOT wag our genitals at one another to make a point. Even it means me taking a chubby… I will suck it up. If I look like a man who made love to his wife last night – it's because I almost did. Turns out he ended up getting too friendly with the teddy bear. First I blow him, then I poke him. Oh, COME ON!)"
wed = Post.create title: "Wednesdays are the bestest", body: "We have unlimited juice? This party is going to be off the hook. Suddenly playing with yourself is a scholarly pursuit? Look at us, crying like a bunch of girls on the last day of camp. Circumvent. It means to go around. Gob: The old reach around. In the mid '90s, Tobias formed a folk music band with Lindsay and Maebe which he called Dr. Funke's 100 Percent Natural Good Time Family Band Solution. The group was underwritten by the Natural Food Life Company, a division of Chem-Grow, an Allen Crayne acqusition, which was part of the Squimm Group. Their motto was simple: We keep you alive. Whoa whoa whoa whoa. Wait. Are you telling me you have a multi-stage trick with hidden identities? However, she mistook the drowsy eye alcohol warning for a winking eye alcohol suggestion."
thurs = Post.create title: "Thursdays are the shit", body: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI."
fri = Post.create title: "Fridays. Need I say more", body: "Accelerator network effects user experience buyer venture iPhone iteration startup equity holy grail burn rate bandwidth. Graphical user interface direct mailing twitter responsive web design assets burn rate. Founders hypotheses bandwidth infrastructure release value proposition mass market conversion business model canvas. Conversion buzz sales accelerator pivot ownership monetization direct mailing metrics hypotheses supply chain. Crowdsource business-to-business business model canvas holy grail value proposition branding buyer beta iPhone equity hackathon. Partner network angel investor crowdsource agile development responsive web design investor innovator focus alpha. Metrics paradigm shift angel investor funding hypotheses crowdfunding social media stock research & development termsheet. User experience termsheet www.discoverartisans.com launch party product management non-disclosure agreement influencer niche market leverage iteration technology validation sales. Gamification virality www.discoverartisans.com iPad holy grail vesting period channels paradigm shift analytics launch party ramen customer alpha. Direct mailing growth hacking seed money launch party responsive web design deployment."
